version: '3.7'

services:

  node_app:
    build: ./gate-simulator
    image: node-app:1.0
    ports:
      - '9999:9999'


  postgres:
    image: library/postgres:12-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DATABASE=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
    # volumes:
    # - ./data_postgres:/var/lib/postgresql/data


  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    # volumes:
    #  - ./data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass